apiVersion: v1
kind: Service
metadata:
  name: endereco-k8s-service
  labels:
    app: endereco-k8s-app
spec:
  type: LoadBalancer
  selector:
    app: endereco-k8s-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 8080